config/routes.rb
ResumeApp::Application.routes.draw do
  root to: 'authentications#home'
  resources :authentications
  devise_for :users, :controllers => {
   :registrations => "registrations",
   :omniauth_callbacks => "users/omniauth_callbacks"
}

  

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  #attr_accessible :user_id, :provider, :uid
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
         
         has_many :authentications
         
  def self.find_or_create_for_twitter(response)
     data = response
     #if user = User.where(twitter_id: "#{data["id"]}").first
        #user
    #else # Create a user with a stub password.
     user = User.new(:email => "twitter+#{data["uid"]}@example.com",
      :password => Devise.friendly_token[0,20])
      user.twitter_id = data["uid"]
      user.twitter_screen_name = data["name"]
      user.twitter_display_name = data["nickname"]
      user.save
      user

     #end
   end
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def index
    @authentications = Authentication.all
  end
  
  
  def home
 
  end

  def create
    @authentication = Authentication.new(user_params)
    if @authentication.save
      redirect_to authentications_url, :notice => "Successfully created authentication."
    else
      render :action => 'new'
    end
  end

  def destroy
    @authentication = Authentication.find(params[:id])
    @authentication.destroy
    redirect_to authentications_url, :notice => "Successfully destroyed authentication."
  end
  
  private
  def user_params
    params.require(:authentication).permit(:user_id, :provider, :uid)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
def twitter
@user = User.find_or_create_for_twitter(env["omniauth.auth"])
flash[:notice] = "Signed in with Twitter successfully."
sign_in_and_redirect @user, :event => :authentication
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/views/authentications/home.html.erb
<% if user_signed_in? %>
 Logged in as <strong><%= current_user.email %></strong>.
 <%= link_to 'Edit profile', edit_user_registration_path %> |
 <%= link_to 'Authentications', authentications_path %> |
 <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
 <%= link_to "Sign up", new_user_registration_path %> |
 <%= link_to "Login", new_user_session_path %>
 <li><%= link_to "Twitter", user_omniauth_authorize_path(:twitter) %></li>
 <li><%= link_to "Facebook", user_omniauth_authorize_path(:facebook) %></li>
<% end %>

app/views/authentications/index.html.erb
<% title "Authentications" %>

<table>
  <tr>
    <th>User</th>
    <th>Provider</th>
    <th>Uid</th>
  </tr>
  <% for authentication in @authentications %>
    <tr>
      <td><%= authentication.user_id %></td>
      <td><%= authentication.provider %></td>
      <td><%= authentication.uid %></td>
      <td><%= link_to "Destroy", authentication, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ResumeApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to image_tag("icons/twitter_32.png"),
user_omniauth_authorize_path(:twitter),
:id => "sign_in_with_twitter" %>

<%= yield %>

</body>
</html>